name: gvxr-ibsim
channels:
    - conda-forge
dependencies:
    - python=3.9
    - scikit-build
    - jupyterlab
    - notebook
    - nb_conda_kernels
    - ipympl
    - ipywidgets
    - matplotlib
    - xraylib
    - scipy
#- opencv
    #- cma
    #- tomopy
    #- numpy
    #- libtiff
    #- pandas
    #- ipykernel
    #- ipython
    #- vtk
    #- jupyterlab
    #- pandas
    #- scikit-learn
    #- scikit-image
    #- imageio
    #- SimpleITK
    #- k3d
    #- numpy-stl
    #- gputil
    #- plotly
    #- jupyterlab>=3
    #- ipywidgets>=7.6
    #- python-kaleido
    - pip
    - pip:
        - xpecgen
        - gatetools
    #    - tabletext
    #    - viewscad
    #    - spekpy
    #    - py-cpuinfo
    #    - pymoo
    #    - chart_studio
